// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      // Las plataformas de escritorio y moviles no estan configuradas.
      // Se devuelve una configuracion vacia para evitar un crash.
      // La app usara Mocks en estas plataformas.
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return _emptyOptions;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Configuracion oficial del proyecto Firebase de PROVEO Nicaragua.
  /// Credenciales para la plataforma web (Flutter Web / PWA).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQif5gmNmFvaiMmt32HQsUFMeUQ-mz8Q',          // Clave API del proyecto Firebase
    appId: '1:248254644384:web:ff90463639b6319ccd89c5',          // ID unico de la app web en Firebase
    messagingSenderId: '248254644384',                             // ID del remitente para Cloud Messaging
    projectId: 'proveonicaragua-43264',                            // ID del proyecto en Firebase Console
    authDomain: 'proveonicaragua-43264.firebaseapp.com',          // Dominio autorizado para autenticacion
    storageBucket: 'proveonicaragua-43264.firebasestorage.app',   // Bucket de Firebase Storage
    measurementId: 'G-290ZBZ2YWZ',                                // ID de medicion para Google Analytics
  );

  static const FirebaseOptions _emptyOptions = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );
}
