// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      // Las plataformas de escritorio y moviles no estan configuradas.
      // Se devuelve una configuracion vacia para evitar un crash.
      // La app usara Mocks en estas plataformas.
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return _emptyOptions;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_osHHZBo3gpWOjeR26VaDkMPm55-Zqls',
    appId: '1:248254644384:web:ff90463639b6319ccd89c5',
    messagingSenderId: '248254644384',
    projectId: 'proveonicaragua-43264',
    authDomain: 'proveonicaragua-43264.firebaseapp.com',
    storageBucket: 'proveonicaragua-43264.firebasestorage.app',
    measurementId: 'G-290ZBZ2YWZ',
  );

  static const FirebaseOptions _emptyOptions = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );
}
